user-21 week1 hw
srcmesh-workshop/kubernetes-adoption-hands-on pull request #25
Opened 2021-01-14 08:20 UTC by goman-jacky

Done!

2021-01-14 11:51 UTC, life1347 requested changes

2021-01-14 11:51 UTC, life1347 commented on homework/week1/user-21.yaml
> +      args: ["-c", "while true; do echo hello; sleep 10; done"]
因為我們要透過 shared volume 讓 busybox 印出環境變數 `DUMMY_DATABASE_PASSWORD` 到 volume 的 index.html，好讓 nginx 可以讀到該檔案，這邊需要修正

2021-01-14 11:51 UTC, life1347 commented on homework/week1/user-21.yaml
> +kind: List
可以用 `kubectl get pod <pod-name> -o yaml` 方式就可以該 pod 的 yaml，如果只使用 `kubectl get pod -o yaml` 會取得當下 namespace 下所有 pod 的 List

2021-01-20 16:32 UTC, goman-jacky commented
hw2

2021-03-25 09:35 UTC, closed without merging