user-24-hw1
srcmesh-workshop/kubernetes-adoption-hands-on pull request #30
Opened 2021-01-15 01:46 UTC by dinner6132

2021-01-18 11:33 UTC, life1347 requested changes

2021-01-18 11:33 UTC, life1347 commented on homework/week1/nginx-svc.yaml
> +      env: testgogo
Service 的 selector 要為 Pod labels 的 subset，由於 Pod 沒有 `env: testgogo` 的 Label，因此實際上這個 service 流量無法送往後端 Pod

2021-01-19 16:14 UTC, dinner6132 reviewed
thanks~~

2021-01-19 16:33 UTC, dinner6132 commented
不知道為什麼hw2出現在這裡的File changed 5 了
有什麼方式可以變成新的pr嗎?
不太會用git 請見諒QQ

2021-01-19 16:34 UTC, dinner6132 commented
是要關掉這個pr後，才能重新再開一個嗎??

2021-01-19 16:51 UTC, life1347 commented
可以 checkout 到新 branch 後再重新發 PR 就不會發到同 PR 的問題

```
git checkout hw2
```

2021-03-25 09:35 UTC, closed without merging