Rocko homework
srcmesh-workshop/kubernetes-adoption-hands-on pull request #5
Opened 2020-10-21 08:42 UTC by roc26002w

## Install

* kubectl create configmap nginx-default-conf --from-file=config/nginx/default.conf
* kubectl create configmap fluent-default-conf --from-file=config/fluent/fluent.conf
* kubectl apply -f .

## 問題 : 
* 我想把 mysql 跟 wordpress 都使用 PersistentVolume mount 到本地的資料夾當編輯，但是 
  * PersistentVolume 的 hostPath 好像只能用絕對路徑，無法使用相對路徑對吧?

* 這樣的目地是為了讓 wordpress 專案在本地更新檔案後，可以自動 sync 進 k8s 的 pod 內就可以直接更新了

2020-10-22 06:37 UTC, life1347 commented
若印象沒錯的話，volume mount path 都只能使用絕對路徑。另外，絕對路徑可以避免人為錯誤，每人對於相對路徑的認知不同，容易造成維護困難

2020-10-22 06:58 UTC, life1347 requested changes
大致上沒有太大問題，可以額外嘗試用 secret 管理 DB 帳密!
(PVC 部分因為是備註解掉的狀態，所以此次沒有額外測試這個部分)

2020-10-22 06:58 UTC, life1347 commented on homework/rocko/config/nginx/default.conf
> +      proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
這個 config 會導致 css 消失的問題，可以換成 hw.md 內的設定檔就會正常

<img width="1140" alt="截圖 2020-10-22 下午2 52 31" src="https://user-images.githubusercontent.com/202578/96835561-5635e080-1476-11eb-90a4-5d8b3b2a6bfc.png">

可以思考為什麼造成這個問題的原因 (暗示在瀏覽器的網址跟 error 的網址)，詳細細節會於週六課堂時講解

2020-10-22 06:58 UTC, life1347 commented on homework/rocko/wordpress-deployment.yaml
> +              value: mysql
可以試著使用 secret 管理這些資訊，並用 env 方式傳入容器內

2020-10-23 06:54 UTC, roc26002w commented on homework/rocko/config/nginx/default.conf
> +      proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
已修正
看起來在連線的時候，是開在 8888 但是 css 連線 port 還是連 80 所以就失效了
感謝提示

2020-10-23 06:55 UTC, roc26002w commented on homework/rocko/wordpress-deployment.yaml
> +              value: mysql
使用 secret 管理來設定了
又練習了一種功能
感謝提醒
XDD

2020-10-23 07:22 UTC, life1347 commented on homework/rocko/config/nginx/default.conf
> +      proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
是的，這部分在使用第三方服務時可能會遇到，由於 wordpress 會將 request 的 host 作為資源傳遞時的網誌，但由於我們是使用 Nginx 做 reverse proxy，因此會導致外部看到的 host 跟實際 wordpress 收到的 host 不同，因此需在 Nginx 利用 proxy_redirect 將 response 的 Location rewrite。

2020-10-23 07:23 UTC, life1347 commented
💯

2020-10-28 08:54 UTC, closed without merging